kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-pvc-nfs
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: media-pv-nfs
  storageClassName: nfs-csi