# TODO https://github.com/kanidm/kanidm/issues/1227
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kanidm-selfsigned
  namespace: {{ .Release.Namespace }}
spec:
  secretName: kanidm-selfsigned-certificate
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  issuerRef:
    kind: Issuer
    name: kanidm-selfsigned
  dnsNames:
    - home.arpa
