app-template:
  defaultPodOptions:
    enableServiceLinks: true
    securityContext:
      fsGroup: 1000
  controllers:
    main:
      containers:
        main:
          image:
            repository: lscr.io/linuxserver/jellyfin
            tag: 10.10.7
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
              spec:
                failureThreshold: 30
                periodSeconds: 5
          resources:
            requests:
              cpu: 64m
              memory: 897Mi
        qbittorrent:
          image:
            repository: lscr.io/linuxserver/qbittorrent
            tag: 5.1.2
          resources:
            requests:
              cpu: 2m
              memory: 10Mi
          env:
            - name: WEBUI_PORT
              value: "8085"
        prowlarr:
          image:
            repository: lscr.io/linuxserver/prowlarr
            tag: 2.0.5
          resources:
            requests:
              cpu: 2m
              memory: 101Mi
        radarr:
          image:
            repository: lscr.io/linuxserver/radarr
            tag: 5.27.5
          resources:
            requests:
              cpu: 2m
              memory: 104Mi
        sonarr:
          image:
            repository: lscr.io/linuxserver/sonarr
            tag: 4.0.15
          resources:
            requests:
              cpu: 2m
              memory: 187Mi
        jellyseerr:
          image:
            repository: docker.io/fallenbagel/jellyseerr
            tag: 2.7.3
          resources:
            requests:
              memory: 208Mi
              cpu: 1m
        sabnzbd:
          image:
            repository: lscr.io/linuxserver/sabnzbd
            tag: latest
          resources:
            requests:
              cpu: 2m
              memory: 101Mi
  service:
    main:
      controller: main
      ports:
        http:
          port: 8096
          protocol: HTTP
          primary: true
        qbittorrent:
          port: 8085
          protocol: HTTP
        prowlarr:
          port: 9696
          protocol: HTTP
        radarr:
          port: 7878
          protocol: HTTP
        sonarr:
          port: 8989
          protocol: HTTP
        jellyseerr:
          port: 5055
          protocol: HTTP
        sabnzbd:
          port: 8080
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &jellyfinHost jellyfin.pjak.me
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
        - host: &qbittorrentHost qbittorrent.pjak.me
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: qbittorrent
        - host: &prowlarrHost prowlarr.pjak.me
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: prowlarr
        - host: &radarrHost radarr.pjak.me
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: radarr
        - host: &sonarrHost sonarr.pjak.me
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: sonarr
        - host: &sabnzbdHost sabnzbd.pjak.me
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: sabnzbd
      tls:
        - secretName: jellyfin-tls-certificate
          hosts:
            - *jellyfinHost
            - *qbittorrentHost
            - *prowlarrHost
            - *radarrHost
            - *sonarrHost
            - *sabnzbdHost
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 50Gi
      advancedMounts:
        main:
          main:
            - path: /config
              subPath: jellyfin/config
            - path: /cache
              subPath: jellyfin/cache
          qbittorrent:
            - path: /config
              subPath: qbittorrent/config
            - path: /downloads
              subPath: qbittorrent/downloads
          prowlarr:
            - path: /config
              subPath: prowlarr/config
          radarr:
            - path: /config
              subPath: radarr/config
            - path: /downloads/complete
              subPath: qbittorrent/downloads/complete
          sonarr:
            - path: /config
              subPath: sonarr/config
            - path: /downloads/complete
              subPath: qbittorrent/downloads/complete
          jellyseerr:
            - path: /app/config
              subPath: jellyseerr/config
          sabnzbd:
            - path: /config
              subPath: sabnzbd/config
    media:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: media-pvc-nfs
      advancedMounts:
        main:
          main:
            - path: /mnt/data
              readOnly: false
          qbittorrent:
            - path: /data
              readOnly: false
          radarr:
            - path: /data
              readOnly: false
          prowlarr:
            - path: /data
              readOnly: false
          jellyseerr:
            - path: /data
              readOnly: false
          sonarr:
            - path: /data
              readOnly: false
          sabnzbd:
            - path: /data
              readOnly: false
