app-template:
  defaultPodOptions:
    enableServiceLinks: true
    securityContext:
      fsGroup: 1000
  controllers:
    main:
      containers:
        main:
          image:
            repository: docker.io/jellyfin/jellyfin
            tag: 10.8.13
        transmission:
          image:
            repository: lscr.io/linuxserver/transmission
            tag: 4.0.5
        prowlarr:
          image:
            repository: lscr.io/linuxserver/prowlarr
            tag: 1.13.3
        radarr:
          image:
            repository: lscr.io/linuxserver/radarr
            tag: 5.3.6
        sonarr:
          image:
            repository: lscr.io/linuxserver/sonarr
            tag: 4.0.2
        jellyseerr:
          image:
            repository: docker.io/fallenbagel/jellyseerr
            tag: 1.7.0
  service:
    main:
      controller: main
      ports:
        http:
          port: 8096
          protocol: HTTP
          primary: true
        transmission:
          port: 9091
          protocol: HTTP
        prowlarr:
          port: 9696
          protocol: HTTP
        radarr:
          port: 7878
          protocol: HTTP
        sonarr:
          port: 8989
          protocol: HTTP
        jellyseerr:
          port: 5055
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &jellyfinHost jellyfin.pjak.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: 8096
        - host: &transmissionHost transmission.pjak.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: 9091
        - host: &prowlarrHost prowlarr.pjak.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: 9696
        - host: &radarrHost radarr.pjak.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: 7878
        - host: &sonarrHost sonarr.pjak.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: 8989
        - host: &jellyseerrHost jellyseerr.pjak.me
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: 5055
      tls:
        - secretName: jellyfin-tls-certificate
          hosts:
            - *jellyfinHost
            - *transmissionHost
            - *prowlarrHost
            - *radarrHost
            - *sonarrHost
            - *jellyseerrHost
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 50Gi
      advancedMounts:
        main:
          main:
            - path: /config
              subPath: jellyfin/config
          transmission:
            - path: /config
              subPath: transmission/config
            - path: /downloads
              subPath: transmission/downloads
          prowlarr:
            - path: /config
              subPath: prowlarr/config
          radarr:
            - path: /config
              subPath: radarr/config
            - path: /downloads/complete
              subPath: transmission/downloads/complete
          sonarr:
            - path: /config
              subPath: sonarr/config
            - path: /downloads/complete
              subPath: transmission/downloads/complete
          jellyseerr:
            - path: /app/config
              subPath: jellyseerr/config
    media:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: media-pvc-nfs
      advancedMounts:
        main:
          main:
            - path: /media
              readOnly: false
          transmission:
            - path: /media
              readOnly: false
          prowlarr:
            - path: /config
              subPath: prowlarr/config
          radarr:
            - path: /media
              readOnly: false
          sonarr:
            - path: /media
              readOnly: false
          jellyseerr:
            - path: /app/config
              subPath: jellyseerr/config
