app-template:
  defaultPodOptions:
    enableServiceLinks: true
    securityContext:
      fsGroup: 1000
  controllers:
    main:
      containers:
        main:
          image:
            repository: lscr.io/linuxserver/jellyfin
            tag: 10.10.7
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
              spec:
                failureThreshold: 30
                periodSeconds: 5
          resources:
            limits:
              memory: 1200Mi
            requests:
              cpu: 64m
              memory: 897Mi
        transmission:
          image:
            repository: lscr.io/linuxserver/transmission
            tag: 4.0.6
          resources:
            limits:
              memory: 177Mi
            requests:
              cpu: 2m
              memory: 10Mi
        prowlarr:
          image:
            repository: lscr.io/linuxserver/prowlarr
            tag: 2.0.5
          resources:
            limits:
              memory: 186Mi
            requests:
              cpu: 2m
              memory: 101Mi
        radarr:
          image:
            repository: lscr.io/linuxserver/radarr
            tag: 5.27.5
          resources:
            requests:
              cpu: 2m
              memory: 104Mi
            limits:
              memory: 200Mi
        sonarr:
          image:
            repository: lscr.io/linuxserver/sonarr
            tag: 4.0.15
          resources:
            limits:
              memory: 254Mi
            requests:
              cpu: 2m
              memory: 187Mi
        jellyseerr:
          image:
            repository: docker.io/fallenbagel/jellyseerr
            tag: 2.7.3
          resources:
            limits:
              memory: 319Mi
            requests:
              memory: 208Mi
              cpu: 1m
  service:
    main:
      controller: main
      ports:
        http:
          port: 8096
          protocol: HTTP
          primary: true
        transmission:
          port: 9091
          protocol: HTTP
        prowlarr:
          port: 9696
          protocol: HTTP
        radarr:
          port: 7878
          protocol: HTTP
        sonarr:
          port: 8989
          protocol: HTTP
        jellyseerr:
          port: 5055
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &jellyfinHost jellyfin.pjak.me
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
        - host: &transmissionHost transmission.pjak.me
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: transmission
        - host: &prowlarrHost prowlarr.pjak.me
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: prowlarr
        - host: &radarrHost radarr.pjak.me
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: radarr
        - host: &sonarrHost sonarr.pjak.me
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: sonarr
        - host: &jellyseerrHost jellyseerr.pjak.me
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: jellyseerr
      tls:
        - secretName: jellyfin-tls-certificate
          hosts:
            - *jellyfinHost
            - *transmissionHost
            - *prowlarrHost
            - *radarrHost
            - *sonarrHost
            - *jellyseerrHost
  persistence:
    data:
      accessMode: ReadWriteOnce
      size: 50Gi
      advancedMounts:
        main:
          main:
            - path: /config
              subPath: jellyfin/config
          transmission:
            - path: /config
              subPath: transmission/config
            - path: /downloads
              subPath: transmission/downloads
          prowlarr:
            - path: /config
              subPath: prowlarr/config
          radarr:
            - path: /config
              subPath: radarr/config
            - path: /downloads/complete
              subPath: transmission/downloads/complete
          sonarr:
            - path: /config
              subPath: sonarr/config
            - path: /downloads/complete
              subPath: transmission/downloads/complete
          jellyseerr:
            - path: /app/config
              subPath: jellyseerr/config
    media:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: media-pvc-nfs
      advancedMounts:
        main:
          main:
            - path: /media
              readOnly: false
          transmission:
            - path: /media
              readOnly: false
          radarr:
            - path: /media
              readOnly: false
          sonarr:
            - path: /media
              readOnly: false
