apiVersion: v2
name: rook-ceph
version: 0.0.0
dependencies:
  - name: rook-ceph
    version: v1.18.4
    repository: https://charts.rook.io/release
  - name: rook-ceph-cluster
    version: v1.18.4
    repository: https://charts.rook.io/release
  # TODO switch to official chart when there is one
  # https://github.com/kubernetes-csi/external-snapshotter/issues/812
  - name: snapshot-controller
    version: 4.1.1
    repository: https://piraeus.io/helm-charts
