apiVersion: batch/v1
kind: Job
metadata:
  name: secret-generator-{{ include (print $.Template.BasePath "/secret-generator/configmap.yaml") . | sha256sum | trunc 7 }}
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: copy-source
          image: busybox:1.36
          command: ["/bin/sh", "-c"]
          args:
            - cp -r /src/. /workdir
          volumeMounts:
            - name: source
              mountPath: /src
              readOnly: true
            - name: workdir
              mountPath: /workdir
      containers:
        - name: secret-generator
          image: golang:1.25-alpine
          workingDir: /workdir
          command:
            - sh
            - -c
          args:
            - |
              go mod tidy
              go run .
          volumeMounts:
            - name: source
              mountPath: /src
              readOnly: true
            - name: workdir
              mountPath: /workdir
      serviceAccount: secret-generator
      volumes:
        - name: source
          configMap:
            name: secret-generator
        - name: workdir
          emptyDir: {}
