kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: library-pvc-nfs
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: library-pv-nfs
  storageClassName: nfs-csi